services:
  neo4j:
    image: neo4j:5.15.0
    volumes:         
        - neo4j_data:/data
        - neo4j_logs:/logs
    environment:
        - NEO4J_AUTH=neo4j/password
        - NEO4J_PLUGINS=["apoc"]
        - NEO4J_dbms_security_procedures_unrestricted=apoc.*
        - NEO4J_dbms_security_procedures_allowlist=apoc.*
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    
  agentic-ai:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_DATABASE=neo4j
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - /app/__pycache__
    working_dir: /app
    command: python customer_deduplication_test.py
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs: